services:
  - type: worker
    name: dora-telegram-bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TIMEZONE
        value: Europe/Madrid
      - key: MAX_HOURS_WITHOUT_WALK
        value: "6"
      - key: QUIET_START
        value: "23:00"
      - key: QUIET_END
        value: "07:30"
